#!/bin/python3.11
import os,sys,helper,config
from initializer import init
from generator import generate

generator_dir=os.path.dirname(os.path.abspath(__file__))
project_dir=os.getcwd()
if(sys.argv[1]=="i" and (sys.argv[2] in config.lang.keys())):
  init(generator_dir,project_dir,sys.argv[2])
  print( "initialized");

elif(sys.argv[1]=="g"):
  print("generating")
  generate(generator_dir,project_dir)

else:
  helper.printHelp()

